version: '3.3'
services:
    rabbitmq:
        image: masstransit/rabbitmq
        container_name: rabbitmq
        restart: unless-stopped
        ports:
            - '15672:15672'
            - '5672:5672'